### ISSUE TITLE
Error: File refs.bib not found in resource path - Visual editor puts "bibliography:" in page YAML header

### ISSUE THREAD

**Issue by rgayler** [tjmahr/notestar#10]
I have just started to play with notestar (having forgotten everything I knew about targets).

I started a notestar project and created one notebook page. The document was building fine.

Then I entered one citation in the notebook page and the build failed with the key message `File refs.bib not found in resource path`.
The build output looked like this:
```
Rscript --vanilla -e "targets::tar_make(reporter = 'verbose'); cli::cat_rule('Makefile finished')"
✓ skip target notebook_output_yaml
✓ skip target notebook_index_yml
• start target entry_2022_04_03_design_rmd
• built target entry_2022_04_03_design_rmd
✓ skip target entry_0000_00_00_references_rmd
✓ skip target notebook_helper_user
✓ skip target spellcheck_exceptions
✓ skip target notebook_index_rmd
✓ skip target notebook_csl_user
• start target notebook_bibliography_user
• built target notebook_bibliography_user
✓ skip target notebook_helper
• start target notebook_rmds
• built target notebook_rmds
✓ skip target notebook_csl_asset
• start target notebook_bibliography_asset
• built target notebook_bibliography_asset
✓ skip target entry_index_md
✓ skip target entry_0000_00_00_references_md
• start target entry_2022_04_03_design_md
• built target entry_2022_04_03_design_md
✓ skip target spellcheck_notebook
✓ skip target notebook_deps_in_index_yml
• start target notebook_mds
• built target notebook_mds
• start target spellcheck_report_results_change
• built target spellcheck_report_results_change
• start target notebook_bookdown_yaml
• built target notebook_bookdown_yaml
• start target spellcheck_report_results
  word                    found
1  VBM 2022-04-03-design.Rmd:13
• built target spellcheck_report_results
• start target notebook


processing file: index.Rmd
  |......................................................................| 100%
   inline R code fragments


output file: index.knit.md

File refs.bib not found in resource path
x error target notebook
• end pipeline: 2.419 seconds
Error in tar_throw_run(target$metrics$error) : 
  pandoc document conversion failed with error 99
In addition: Warning messages:
1: cannot remove file 'notebook.tmp.html', reason 'No such file or directory' 
2: 1 targets produced warnings. Run tar_meta(fields = warnings) for the messages. 
Error in `tar_throw_run()`:
! callr subprocess failed: pandoc document conversion failed with error 99
```

I eventually worked out that the cause of the problem was using `Insert citation` in the Rstudio visual editor. This inserted the line `bibliography: refs.bib` in the YAML header of the notebook page Rmd file. Deleting that line makes the problem go away.

Would it be possible to either automatically delete that line from the YAML header or to issue a warning if it's detected?

Thanks

**Comment by tjmahr** [comment]
The visual editor adds the line to the yaml of an individual entry .Rmd?

**Comment by rgayler** [comment]
> The visual editor adds the line to the yaml of an individual entry .Rmd?

Yes. This is independent of `notestar`, so not invoking it below.

Reproducing it (I use Zotero as my references manager.):

RStudio 2022.02.1 Build 461
zotero 6.0.4

1. Check RStudio global options for citations (RStudio | Tools | Global Options | R Markdown | Citations)  
![Screenshot from 2022-04-07 11-34-35](https://user-images.githubusercontent.com/5409051/162102700-db6e5c10-327d-40b5-bf99-44b4b63b807e.png)
2. Create new project (new directory; git FALSE; renv FALSE)
3. Start zotero running
4. Check RStudio project options for citations (RStudio | Tools | Project Options | R Markdown)
![Screenshot from 2022-04-07 12-32-59](https://user-images.githubusercontent.com/5409051/162108837-f810fa10-bc51-4ec3-9482-98564e6ae846.png)
5. Create new R Markdown document (RStudio | File | New File | R Markdown)
![Screenshot from 2022-04-07 12-17-00](https://user-images.githubusercontent.com/5409051/162107173-ff6a8636-e3fa-446a-a87c-bdf678bb40c0.png)
6. Go to the editor for the new R Markdown document; switch to visual mode; check the YAML header
![Screenshot from 2022-04-07 12-23-51](https://user-images.githubusercontent.com/5409051/162107877-65070357-d517-4521-aa81-9ed3b63ae567.png)
7. Go to somewhere in the text of the R Markdown document and add a citation using the RStudio visual mode citation tool. (The "Create bibliography" field is pre-filled with `references.bib`. This writes the citation entries to the named file.)
![Screenshot from 2022-04-07 12-27-01](https://user-images.githubusercontent.com/5409051/162108380-0f279b30-9ac7-485b-af85-b5f8dd6e7807.png)
8. Check the R Markdown document. The citation has been added to the text and  `bibliography: references.bib` has been added to the YAML header.
![Screenshot from 2022-04-07 12-30-29](https://user-images.githubusercontent.com/5409051/162108551-8fb7fc0c-481e-48c5-bb7d-cee53d3ccec3.png)

I presume that the citation tool is responsible for adding the bibliography line to the YAML header.

**Comment by rgayler** [comment]
Many thanks!

**Comment by rgayler** [comment]
Many thanks!
