### ISSUE TITLE
Bookdown support?

### ISSUE THREAD

**Issue by gregmacfarlane** [tjmahr/notestar#3]
I'm really glad you have worked on this; I'm just getting into `targets` today, but I'm a long-time `bookdown` user. How difficult would it be to adapt this package for bookdown? I see you mention it on your README, but that it seems to mostly work on individual Rmd docs in a separate folder? Maybe I'm wrong?

**Comment by tjmahr** [comment]
This might be a better starting point:

https://github.com/robitalec/targets-parameterized-bookdown
